workflows:
  main:
    name: Main workflow
    environment:
   
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_ALLOW_PROVISIONING_UPDATES: 'true'
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          flutter pub get
          cd ios
          pod repo update
          pod update GoogleAppMeasurement
          pod install

      - name: Build iOS app
        script: flutter build ios --release
my-workflow:
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        beta_groups:
          - Beta Testers
