workflows:
  main:
    name: Main workflow
    environment:
      vars:
        FLUTTER_CHANNEL: stable
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          flutter pub get
          cd ios
          pod repo update
          # Use a specific version for Firebase/Auth to avoid version conflicts
          pod 'Firebase/Auth', '10.12.0'
          pod install
      - name: Build iOS app
        script: flutter build ios --release
