workflows:
  main:
    name: Main workflow
    environment:
   
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_ALLOW_PROVISIONING_UPDATES: 'true'
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          flutter pub get
          cd ios
          pod repo update
          pod update GoogleAppMeasurement
          pod install

      - name: Clean Xcode Build
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Caches/CocoaPods
          flutter clean

      - name: Build iOS app
        script: |
          flutter build ios --release -t lib/main.dart
          xcodebuild clean build -allowProvisioningUpdates -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -destination 'platform=iOS Simulator,OS=14.5,name=iPhone 11' CODE_SIGN_STYLE=Automatic

my-workflow:
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        beta_groups:
          - Beta Testers
